### PR TITLE
Add OTA config for shamrock

### PR DESCRIPTION
**Pull request by kaanyigitkulahli**

### CODE REVIEW

**Comment by kaanyigitkulahli** [comment]
@ankurpandeyvns

**Comment by chautruongthinh** [comment]
You shouldn't use AFH link because it will die soon!!

**Comment by ankurpandeyvns** [comment]
You can use XDA for direct links too. I'm merging this but make sure you use xda next time.

**Comment by kaanyigitkulahli** [comment]
Of course, I will add Xda links soon.

**Pull request merged**
